name: stdin_line
description: It returns a stdin line split into words.
version: 1.0.0
# homepage: https://www.example.com
author: Fernando Trigoso <fertrig@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

# dev_dependencies:
#   pedantic: ^1.0.0
#   test: ^1.0.0
